#!/bin/bash
DIFF=`diff amdhome.ucdavis.edu temp | tail -n +2`
declare -A DOMAINS='([amdhome.ucdavis.edu]="Samuel Tseng, amdtseng@ucdavis.edu:A, la6amdhome@gmail.com:B, la6amdhome@googlemail.com" )'
domain=amdhome.ucdavis.edu

IFS=':' read -r -a TO <<< "${DOMAINS[$domain]}"

declare -p TO

for admin in ${!TO[@]}
do
	TO[$admin]=`echo "${TO[admin]}" | awk -F ',' '{print $2}'`
done

TO=`IFS=$', '; echo "${TO[*]}"`

DIFF=`echo "$DIFF" | sed 's/< /deleted\t/g' | sed 's/> /added\t/g'`

(
echo "From: dcop-bot@ucdavis.edu";
echo "To:$TO";
echo "Subject: DNS Entries Changed for $domain";

echo "
Hello Admin's,

The following change(s) have been detected for the domain $domain.

$DIFF

If these changes were intentional please let operations know to update the saved DNS entries for DNS_Notify on dcop-bot

Please no not reply or send emails back to this email address. This inbox is not monitored.

Thanks,
Operations Team
Hotline: (530) 752-1566
";
) | sendmail -t